contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = true
baseURL = "/"
languageCode = "en-us"
title = "La Razante"
canonifyURLs = true
googleAnalytics= ""

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "LA RAZANTE es una película que narra un drama común no solo en sociedades como las de República Dominicana sino en cualquier parte del mundo"
  author = "Enzo Vezzaro"
  variables = "Yes"
  english = "EN"
  logo = "/img/logo.svg"
